# This is a basic workflow to help you get started with Actions

name: socdoc-generator

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  login:
    runs-on: ubuntu-latest
    steps:
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
     
     - name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout Repo
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
    
      - name: Pip Installer
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt

      - name: Run socdocs script
      # cd $GITHUB_WORKSPACE/socdocs/
        run: |
          python exportparser.py
        
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "dpbinfosec/socdocs"
          LATEST: "true"
       
